var phoneNo=123456789;
var handset="Poco X2";
var isAndroid=true;
console.log("phone no. :",phoneNo,",type :",typeof phoneNo);
console.log("handset :",handset,",type :",typeof handset);
console.log("isAndroid :",isAndroid,",type :",typeof isAndroid);
console.log("");
console.log("Differance betweet null vs unsefined :");
var value1=null;
var value2;
console.log(" null                |     undefined");
console.log("===========================================");
console.log("value=",value1,"         |   value=",value2);
console.log( "Return type :",typeof value1,"| Return type :",typeof value2);